### ISSUE TITLE
The player wants to see his teammates on the map

### ISSUE THREAD

**Issue by ghost** [Lux0r87/TacticalTeamCombat#1]
#### Tasks
- [x] Create unit markers - **#33**
- [x] Update the position of the unit markers - **#18**
- [x] Toggle the visibility of the unit markers - **#12** CANCELED!
- [x] Hide unit markers if the unit is inside of a vehicle and not the driver - **#13**
#### Notes

Show unit markers only for units which are in the same team as the player

**Comment by BauerMitFackel** [comment]
- [ ] Create unit markers on the map
- [ ] Toggle the visibility of the unit marker by doubleclick on the group marker
- [ ] Colorize the markers depending on the side color
