### ISSUE TITLE
Reward System

### ISSUE THREAD

**Issue by Lux0r87** [Lux0r87/TacticalTeamCombat#10]
#### Stories
- [x] The player wants to see his points - **#14**
- [ ] The player wants to get points - **#22**
- [x] The player can loose points - **#25**

**Comment by ghost** [comment]
Maybe points is a bad name. In most games the term points refer to sectors or areas and not money. This could confuse the players and hinder communication between them.
