### ISSUE TITLE
The players want different fire teams

### ISSUE THREAD

**Issue by Lux0r87** [Lux0r87/TacticalTeamCombat#11]
Adjust the fire teams and all affected scripts for the new team concept:
#### Tasks
- [x] Change fire team - Platoon Lead - **#28**
- [x] Add fire team - Recon - **#29**
- [x] Add fire team - Heavy Weapon Team - **#30**   CANCELED!
- [x] Change fire teams - Archer/Knight - **#60**

**Comment by Lux0r87** [comment]
Some of the affected scripts are:
- Unit markers
- Respawn gear
- Virtual Arsenal / Shop
