### ISSUE TITLE
The player wants to get points

### ISSUE THREAD

**Issue by Lux0r87** [Lux0r87/TacticalTeamCombat#22]
The player wants to get points for the reward system.
#### Tasks
- [x] Players get a basic income - **#16**
- [x] Cap the basic income - **#110**
- [x] Players get points for capturing a sector - **#17**
- [x] Players get points for defending a sector - **#77**
- [ ] Medics get points for reviving team mates - **#19**
- [ ] Combat engineers get points for repairing vehicles - **#20**
- [ ] Pilots get points for transporting players - **#21**
