### ISSUE TITLE
Introduction and Help

### ISSUE THREAD

**Issue by ghost** [Lux0r87/TacticalTeamCombat#26]
#### Stories
- [x] The player wants to see a welcome message - **#2**
- [ ] The player wants a notice board - **#3**
- [ ] The player wants a briefing - **#6**
