### ISSUE TITLE
The player wants to buy vehicles at his base

### ISSUE THREAD

**Issue by Lux0r87** [Lux0r87/TacticalTeamCombat#32]
#### Tasks
- [x] Define the prices for vehicles - **#31**
- [x] Define the available vehicles for the roles - **#40**
#### Bugs
- [x] The inventory of vehicles is not cleared - **#102**
