### ISSUE TITLE
Create unit markers

### ISSUE THREAD

**Issue by ghost** [Lux0r87/TacticalTeamCombat#33]
Belongs to #1 
#### Subtasks
- [ ] Create a local marker for every teammate of the player
- [ ] Add the marker name as variable to the corresponding unit
- [ ] Set the marker type depending on the side / role
- [ ] Set the marker size to the size of the icon
- [ ] Set the marker color to the color of the side
