### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by Lux0r87** [Lux0r87/TacticalTeamCombat#36]
#### Stories
- [x] The player wants to buy gear at his base - **#7**
- [x] The player wants to buy vehicles at his base - **#32**
- [x] The player wants to buy helicopters at his base - **#35**
- [x] The player wants to save/load his shopping cart - **#103**
- [x] The player wants to buy gear at the sectors - **#123**
- [ ] The player wants to buy vehicles at the sectors - **#125**
#### Tasks
- [x] Balance the prices for armed vehicles - **#98**
- [x] Reduce the price for the cheapest marksman rifle - **#100**
- [x] Allow the most roles to buy the cheapest AT - **#101**
- [ ] Add a "Add to cart" button to the shop - **#104**
- [ ] Enable players to add articles to shopping cart by drag and drop - **#114**
