### ISSUE TITLE
Sector Control (SC)

### ISSUE THREAD

**Issue by ghost** [Lux0r87/TacticalTeamCombat#42]
#### Notes
- The system uses triggers to represent the sectors.
- The sectors are connected between themselves.
#### Stories
- [x] The player wants sectors at strategic locations - **#45**
- [x] The player wants a mobile sector - **#48**
- [x] The player wants to spawn at the sectors - **#51**
- [x] The player wants to capture the sectors - **#53**
- [x] The sectors should be protected by AI - **#56**
- [x] The admin wants that the mission ends automatically - **#59**
- [x] The admin wants tasks for the sectors - **#70**
- [x] The player wants to see the connections between the sectors - **#118**
- [x] The admin don't want to allow UAVs/UGVs to capture sectors - **#120**

**Comment by Lux0r87** [comment]
#### Patterns

##### 7 Sectors

![area layout - 7 sectors](https://cloud.githubusercontent.com/assets/11304010/7730791/946b59a4-ff1c-11e4-81b9-9e9111f5fd55.png)

##### 9 Sectors

![area layout - 9 sectors](https://cloud.githubusercontent.com/assets/11304010/7730793/99f70c42-ff1c-11e4-9fa6-293e7080c3c8.png)

**Comment by BauerMitFackel** [comment]
#### TODO
- [ ] Setup test layout in Paros
- [ ] Choose Vehicle for Mobile Sector
- [ ] Show Sectors on map (only own sectors + connected enemy/neutral)

**Comment by Lux0r87** [comment]
![gameloop](https://cloud.githubusercontent.com/assets/11304010/7092937/a4ffbd22-dfb5-11e4-9e49-a269cf6cb769.png)
