### ISSUE TITLE
The sectors should be protected by AI

### ISSUE THREAD

**Issue by Lux0r87** [Lux0r87/TacticalTeamCombat#56]
#### Tasks
- [x] Spawn AI at the sectors - **#54**
- [x] Allow AI to recapture their own sectors - **#55**
- [x] Define different types of sector patrols - **#112**
- [x] Repawn the AI at the sectors - **#113**
