### ISSUE TITLE
The player wants to buy gear at his base

### ISSUE THREAD

**Issue by ghost** [Lux0r87/TacticalTeamCombat#7]
#### Tasks
- [x] Define the prices for the gear - **#37**
- [x] Highlight compatible magazines/attachments - **#38** CANCELED !
- [x] Define the available gear for the roles - **#39**
- [x] Create a 'Shop' in the base - **#93**
