### ISSUE TITLE
Lock the inventory for the players

### ISSUE THREAD

**Issue by Lux0r87** [Lux0r87/TacticalTeamCombat#82]
#### Subtasks
- [x] Lock all backpacks
- [x] Lock dead AI
- [x] Lock objects (e.g. vehicles)
