### ISSUE TITLE
Create a teleport

### ISSUE THREAD

**Issue by Lux0r87** [Lux0r87/TacticalTeamCombat#86]
Allow the players to teleport to their own sectors.
#### Subtasks
- [x] Write a teleport function - **#85**
- [x] Create a UI for the teleport - **#84**
- [x] Create a 'teleport facility' in the base - **#92**
